// Step 3 of M30: backup.home agent command. Pre-pass `du -sb /home/<u>`
// to enforce the 50 GiB ceiling, then `restic backup` with the canonical
// account_backup tag set.
//
// The 50 GiB ceiling is logical content size, not repo size — restic's
// dedup will compress the snapshot far below 50 GiB, but operators
// asking to back up a 200 GB account are pointed at SFTP+rsync per
// ADR-0075.
package commands

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strconv"
	"strings"

	"git.linux-hosting.co.il/shukivaknin/jabali2/internal/backup"
)

// HomeBackupCeilingBytes is the hard refuse-to-backup threshold.
const HomeBackupCeilingBytes uint64 = 50 * 1024 * 1024 * 1024

// HomeExcludeFile is the install-managed exclude list. Generated by
// install_backup_foundation in install.sh (Step 1 follow-up — for now
// the file may not exist; missing exclude file is non-fatal).
const HomeExcludeFile = "/etc/jabali-panel/restic-excludes.list"

type backupHomeParams struct {
	JobID    string `json:"job_id"`
	UserID   string `json:"user_id"`
	Username string `json:"username"`
}

type backupHomeResult struct {
	SnapshotID     string `json:"snapshot_id"`
	ParentSnapshot string `json:"parent_snapshot,omitempty"`
	BytesAdded     uint64 `json:"bytes_added"`
	BytesTotal     uint64 `json:"bytes_total"`
	LogicalBytes   uint64 `json:"logical_bytes"`
}

func backupHomeHandler(ctx context.Context, raw json.RawMessage) (any, error) {
	var req backupHomeParams
	if err := json.Unmarshal(raw, &req); err != nil {
		return nil, bkInvalidArg("malformed JSON body")
	}
	if !ulidRE.MatchString(req.JobID) {
		return nil, bkInvalidArg("job_id must be a 26-char ULID")
	}
	if !ulidRE.MatchString(req.UserID) {
		return nil, bkInvalidArg("user_id must be a 26-char ULID")
	}
	if !backupUsernameRE.MatchString(req.Username) {
		return nil, bkInvalidArg("username must match ^[a-z][a-z0-9_-]{0,31}$")
	}

	homePath := filepath.Join("/home", req.Username)
	if _, err := os.Stat(homePath); err != nil {
		return nil, bkInvalidArg(fmt.Sprintf("user home not found: %s", homePath))
	}

	// Pre-pass: du -sb to refuse-before-ingest above 50 GiB.
	logical, err := duBytes(ctx, homePath)
	if err != nil {
		return nil, bkInternal("du pre-pass", err)
	}
	if logical > HomeBackupCeilingBytes {
		return nil, &resticCeilingExceeded{path: homePath, logical: logical, ceiling: HomeBackupCeilingBytes}
	}

	if _, err := bkResticBin(); err != nil {
		return nil, bkInternal("restic missing", err)
	}

	c := backup.New(backup.DefaultConfig())
	tags := backup.AccountBackupTags(req.JobID, req.UserID, backup.StageHome)

	opts := backup.BackupOpts{
		Paths: []string{homePath},
		Tags:  tags,
	}
	if _, err := os.Stat(HomeExcludeFile); err == nil {
		opts.ExcludeFile = HomeExcludeFile
	}
	summary, err := c.Backup(ctx, opts)
	if err != nil {
		return nil, bkInternal("restic backup", err)
	}
	return backupHomeResult{
		SnapshotID:   summary.SnapshotID,
		BytesAdded:   summary.DataAdded,
		BytesTotal:   summary.TotalBytesProcessed,
		LogicalBytes: logical,
	}, nil
}

// duBytes runs `du -sb <path>` and returns the byte count. Hard-fails
// on a non-zero exit (could be permission-denied; treat as scan failure
// rather than silently passing).
func duBytes(ctx context.Context, path string) (uint64, error) {
	out, err := exec.CommandContext(ctx, "du", "-sb", path).Output()
	if err != nil {
		return 0, fmt.Errorf("du -sb %s: %w", path, err)
	}
	fields := strings.Fields(strings.TrimSpace(string(out)))
	if len(fields) == 0 {
		return 0, fmt.Errorf("du -sb %s: empty output", path)
	}
	n, err := strconv.ParseUint(fields[0], 10, 64)
	if err != nil {
		return 0, fmt.Errorf("parse du output %q: %w", fields[0], err)
	}
	return n, nil
}

// resticCeilingExceeded is the typed error returned when an account's
// logical size exceeds the 50 GiB refusal threshold. Callers surface
// it as agentwire.CodeFailedPrecondition.
type resticCeilingExceeded struct {
	path    string
	logical uint64
	ceiling uint64
}

func (e *resticCeilingExceeded) Error() string {
	return fmt.Sprintf("backup refused: %s is %d bytes, ceiling is %d bytes (50 GiB)", e.path, e.logical, e.ceiling)
}

func init() {
	Default.Register("backup.home", backupHomeHandler)
}
