// Agent commands for SPA-driven M35 migrations:
//
//   migration.secrets_write    — writes /etc/jabali-panel/migration-
//                                secrets/<job-id>.env with given content
//                                (root:jabali 0640 per ADR-0094 §
//                                "tracked risks").
//   migration.pull_source_run  — systemd-run-launches
//                                'jabali migrate pull-source --job-id'
//                                so the SSH pull + extract survive
//                                a panel-api restart.
//   migration.import_run       — systemd-run-launches
//                                'jabali migrate import --job-id ...'
//                                so the multi-stage restore likewise
//                                survives.
//
// All three run as root (agent runs as root). Validation:
//   - job_id: ULID-shape (26 alphanumeric)
//   - secrets file path: under /etc/jabali-panel/migration-secrets/
//   - systemd unit name: prefixed jabali-migrate-<verb>-<jobid>
//
// Pattern matches system.update_run (M29) — same transient-unit
// approach + reset-failed before each spawn so a previous run's
// failed state doesn't block ALREADY_EXISTS.
package commands

import (
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strings"
	"time"

	"git.linux-hosting.co.il/shukivaknin/jabali2/agentwire"
)

const migrationSecretsBaseDir = "/etc/jabali-panel/migration-secrets"

var migrationJobIDRe = regexp.MustCompile(`^[0-9A-Za-z]{26}$`)

// migrationSecretsWriteParams takes either a password OR a private-key
// blob (operator's choice). Both forms are written into the env file
// in the format `loadSecret` (cpanel/discover.go) expects.
type migrationSecretsWriteParams struct {
	JobID         string `json:"job_id"`
	SSHPassword   string `json:"ssh_password,omitempty"`
	SSHPrivateKey string `json:"ssh_private_key,omitempty"`
}

func init() {
	Default.Register("migration.secrets_write", migrationSecretsWriteHandler)
	Default.Register("migration.pull_source_run", migrationPullSourceRunHandler)
	Default.Register("migration.import_run", migrationImportRunHandler)
}

func migrationSecretsWriteHandler(_ context.Context, raw json.RawMessage) (any, error) {
	var p migrationSecretsWriteParams
	if err := json.Unmarshal(raw, &p); err != nil {
		return nil, &agentwire.AgentError{Code: agentwire.CodeInvalidArgument, Message: "malformed JSON: " + err.Error()}
	}
	if !migrationJobIDRe.MatchString(p.JobID) {
		return nil, &agentwire.AgentError{Code: agentwire.CodeInvalidArgument, Message: "job_id must be 26-char alnum (ULID)"}
	}
	if p.SSHPassword == "" && p.SSHPrivateKey == "" {
		return nil, &agentwire.AgentError{Code: agentwire.CodeInvalidArgument, Message: "ssh_password or ssh_private_key required"}
	}
	if err := os.MkdirAll(migrationSecretsBaseDir, 0o750); err != nil {
		return nil, &agentwire.AgentError{Code: agentwire.CodeInternal, Message: "mkdir secrets dir: " + err.Error()}
	}
	target := filepath.Join(migrationSecretsBaseDir, p.JobID+".env")
	tmp := target + ".tmp"
	var b strings.Builder
	b.WriteString("# Generated by SPA migration secrets-upload (M35)\n")
	b.WriteString("# Reaped on terminal job state via WipeJobSecret.\n")
	if p.SSHPassword != "" {
		b.WriteString("SSH_PASSWORD=")
		b.WriteString(p.SSHPassword)
		b.WriteByte('\n')
	}
	if p.SSHPrivateKey != "" {
		// loadSecret in cpanel/discover.go splits the env file on
		// '\n' then strings.Cut(line, "=") — that only sees the
		// first line of a multi-line PEM key. Encode the whole
		// PEM blob as standard base64 (single-line) so the parser
		// recovers it via SSH_PRIVATE_KEY_B64.
		b.WriteString("SSH_PRIVATE_KEY_B64=")
		b.WriteString(base64.StdEncoding.EncodeToString(
			[]byte(strings.TrimRight(p.SSHPrivateKey, "\n") + "\n"),
		))
		b.WriteByte('\n')
	}
	if err := os.WriteFile(tmp, []byte(b.String()), 0o640); err != nil {
		return nil, &agentwire.AgentError{Code: agentwire.CodeInternal, Message: "write tmp: " + err.Error()}
	}
	if err := os.Rename(tmp, target); err != nil {
		_ = os.Remove(tmp)
		return nil, &agentwire.AgentError{Code: agentwire.CodeInternal, Message: "rename: " + err.Error()}
	}
	// Best-effort group ownership so the panel-api can read the
	// file (root:jabali 0640). Failure is non-fatal — rotate path
	// fires the same chown on jabali update.
	_ = exec.Command("chown", "root:jabali", target).Run()
	return map[string]string{"path": target}, nil
}

type migrationPullSourceRunParams struct {
	JobID   string `json:"job_id"`
	SSHUser string `json:"ssh_user,omitempty"` // defaults to 'root'
}

type migrationRunResponse struct {
	Unit      string `json:"unit"`
	StartedAt string `json:"started_at"`
}

func migrationPullSourceRunHandler(ctx context.Context, raw json.RawMessage) (any, error) {
	var p migrationPullSourceRunParams
	if err := json.Unmarshal(raw, &p); err != nil {
		return nil, &agentwire.AgentError{Code: agentwire.CodeInvalidArgument, Message: "malformed JSON: " + err.Error()}
	}
	if !migrationJobIDRe.MatchString(p.JobID) {
		return nil, &agentwire.AgentError{Code: agentwire.CodeInvalidArgument, Message: "job_id must be 26-char alnum (ULID)"}
	}
	sshUser := p.SSHUser
	if sshUser == "" {
		sshUser = "root"
	}
	if !looksLikeUnixUsername(sshUser) {
		return nil, &agentwire.AgentError{Code: agentwire.CodeInvalidArgument, Message: "ssh_user looks unsafe"}
	}
	unit := fmt.Sprintf("jabali-migrate-pull-%s.service", p.JobID)
	_ = exec.CommandContext(ctx, "systemctl", "reset-failed", unit).Run()
	startedAt := time.Now().UTC()
	cmd := exec.CommandContext(ctx, "systemd-run",
		"--unit="+unit,
		"--no-block",
		"--collect",
		"/usr/local/bin/jabali", "migrate", "pull-source",
		"--job-id="+p.JobID,
		"--ssh-user="+sshUser,
	)
	out, err := cmd.CombinedOutput()
	if err != nil {
		return nil, &agentwire.AgentError{Code: agentwire.CodeInternal, Message: fmt.Sprintf("systemd-run: %v: %s", err, string(out))}
	}
	return migrationRunResponse{Unit: unit, StartedAt: startedAt.Format(time.RFC3339Nano)}, nil
}

type migrationImportRunParams struct {
	JobID           string `json:"job_id"`
	TargetUser      string `json:"target_user"`
	TargetEmail     string `json:"target_email,omitempty"`
	TargetPassword  string `json:"target_password,omitempty"`
	TargetPackageID string `json:"target_package_id,omitempty"`
}

func migrationImportRunHandler(ctx context.Context, raw json.RawMessage) (any, error) {
	var p migrationImportRunParams
	if err := json.Unmarshal(raw, &p); err != nil {
		return nil, &agentwire.AgentError{Code: agentwire.CodeInvalidArgument, Message: "malformed JSON: " + err.Error()}
	}
	if !migrationJobIDRe.MatchString(p.JobID) {
		return nil, &agentwire.AgentError{Code: agentwire.CodeInvalidArgument, Message: "job_id must be 26-char alnum (ULID)"}
	}
	if !looksLikeUnixUsername(p.TargetUser) {
		return nil, &agentwire.AgentError{Code: agentwire.CodeInvalidArgument, Message: "target_user looks unsafe"}
	}
	args := []string{
		"--unit=" + fmt.Sprintf("jabali-migrate-import-%s.service", p.JobID),
		"--no-block",
		"--collect",
		"/usr/local/bin/jabali", "migrate", "import",
		"--job-id=" + p.JobID,
		"--target-user=" + p.TargetUser,
	}
	if p.TargetEmail != "" {
		args = append(args, "--target-email="+p.TargetEmail)
	}
	if p.TargetPassword != "" {
		args = append(args, "--target-password="+p.TargetPassword)
	}
	if p.TargetPackageID != "" {
		args = append(args, "--target-package-id="+p.TargetPackageID)
	}
	unit := fmt.Sprintf("jabali-migrate-import-%s.service", p.JobID)
	_ = exec.CommandContext(ctx, "systemctl", "reset-failed", unit).Run()
	startedAt := time.Now().UTC()
	cmd := exec.CommandContext(ctx, "systemd-run", args...)
	out, err := cmd.CombinedOutput()
	if err != nil {
		return nil, &agentwire.AgentError{Code: agentwire.CodeInternal, Message: fmt.Sprintf("systemd-run: %v: %s", err, string(out))}
	}
	return migrationRunResponse{Unit: unit, StartedAt: startedAt.Format(time.RFC3339Nano)}, nil
}

// looksLikeUnixUsername — defensive whitelist on operator-supplied
// usernames passed straight to systemd-run argv. Same shape the
// directadmin/Hestia packages use.
func looksLikeUnixUsername(s string) bool {
	if len(s) < 1 || len(s) > 32 {
		return false
	}
	for i, r := range s {
		switch {
		case r >= 'a' && r <= 'z':
		case r >= '0' && r <= '9' && i > 0:
		case r == '-' || r == '_':
		default:
			return false
		}
	}
	return true
}
