<?php
// jabali-sso-__JABALI_NONCE__.php — auto-generated by jabali-agent for Joomla install __JABALI_INSTALL_ID__.
// Self-deleting single-use admin login. See ADR-0040.
//
// Joomla bootstrap here targets the frontend site app (not administrator/)
// because the SSO file lives at the site webroot. plg_user_joomla's
// onUserLogin handler writes the shared session so following redirects
// to /administrator/ find the operator already authenticated.

declare(strict_types=1);

// 1. Reject speculative navigation + non-GET. See ADR-0040.
$secPurpose = $_SERVER['HTTP_SEC_PURPOSE'] ?? '';
$purpose    = $_SERVER['HTTP_PURPOSE']     ?? '';
$xMoz       = $_SERVER['HTTP_X_MOZ']       ?? '';
$xPurpose   = $_SERVER['HTTP_X_PURPOSE']   ?? '';
if ($secPurpose !== ''
 || $purpose === 'prefetch'
 || stripos($xMoz, 'prefetch') !== false
 || $xPurpose === 'preview'
 || ($_SERVER['REQUEST_METHOD'] ?? 'GET') !== 'GET') {
    http_response_code(204);
    exit;
}

// 2. Atomic lock claim.
$lock = @fopen(__FILE__, 'r');
if ($lock === false || !flock($lock, LOCK_EX | LOCK_NB)) {
    http_response_code(409);
    exit;
}

// 3. Inline TTL check.
if (filemtime(__FILE__) + __JABALI_TTL_SECONDS__ < time()) {
    http_response_code(410);
    exit;
}

// 4. Bootstrap Joomla. JPATH_BASE must be defined before framework.php
//    pulls in the rest. The agent bakes the install root in at write
//    time so the constants are absolute and don't depend on __DIR__
//    (which would fail if the SSO file were moved).
define('_JEXEC', 1);
define('JPATH_BASE', __JABALI_INSTALL_PATH__);
require_once JPATH_BASE . '/includes/defines.php';
require_once JPATH_BASE . '/includes/framework.php';

use Joomla\CMS\Factory;
use Joomla\CMS\User\User;
use Joomla\CMS\User\UserHelper;
use Joomla\CMS\Plugin\PluginHelper;

// 5. Resolve the admin user by username.
$admin_username = __JABALI_ADMIN_USERNAME__;
$userId = UserHelper::getUserId($admin_username);
if (!$userId) {
    error_log('jabali-sso: joomla admin lookup failed for install __JABALI_INSTALL_ID__');
    http_response_code(404);
    exit;
}
$user = User::getInstance($userId);
if (!$user->authorise('core.admin')) {
    error_log('jabali-sso: joomla user lacks core.admin for install __JABALI_INSTALL_ID__');
    http_response_code(403);
    exit;
}

// 6. Trigger onUserLogin across every user plugin. plg_user_joomla's
//    handler sets the session + fires the auth cookie. This is the
//    same path the login form uses once the password has been verified;
//    we skip the password check because the 256-bit filename is the
//    capability (ADR-0040).
$app = Factory::getApplication('site');
PluginHelper::importPlugin('user');

$response = new \stdClass();
$response->status     = \Joomla\CMS\Authentication\Authentication::STATUS_SUCCESS;
$response->type       = 'jabali-sso';
$response->username   = $user->username;
$response->email      = $user->email;
$response->fullname   = $user->name;
$response->language   = $user->getParam('language', '');
$response->timezone   = $user->getParam('timezone', '');
$options = [
    'remember' => false,
    'action'   => 'core.login.admin',
];
$results = $app->triggerEvent('onUserLogin', [(array) $response, $options]);

// 7. Audit + referrer guard.
error_log('jabali-sso: joomla admin login completed for install __JABALI_INSTALL_ID__');
header('Referrer-Policy: no-referrer');

// 8. Unlink LAST.
@unlink(__FILE__);

// 9. Redirect into administrator/. Use Uri::base() if available so
//    subdir installs land at /<subdir>/administrator/; otherwise fall
//    back to a relative path.
if (class_exists('Joomla\\CMS\\Uri\\Uri')) {
    $base = rtrim(\Joomla\CMS\Uri\Uri::base(true), '/');
    header('Location: ' . $base . '/administrator/');
} else {
    header('Location: administrator/');
}
exit;
