<?php
// jabali-sso-__JABALI_NONCE__.php — auto-generated by jabali-agent for Drupal install __JABALI_INSTALL_ID__.
// Self-deleting single-use admin login. See ADR-0040.

declare(strict_types=1);

// 1. Reject speculative navigation (prefetch / prerender / preview) and
//    non-GET methods before consuming any single-use state. See ADR-0040
//    and sso_template_wordpress.php for the full rationale.
$secPurpose = $_SERVER['HTTP_SEC_PURPOSE'] ?? '';
$purpose    = $_SERVER['HTTP_PURPOSE']     ?? '';
$xMoz       = $_SERVER['HTTP_X_MOZ']       ?? '';
$xPurpose   = $_SERVER['HTTP_X_PURPOSE']   ?? '';
if ($secPurpose !== ''
 || $purpose === 'prefetch'
 || stripos($xMoz, 'prefetch') !== false
 || $xPurpose === 'preview'
 || ($_SERVER['REQUEST_METHOD'] ?? 'GET') !== 'GET') {
    http_response_code(204);
    exit;
}

// 2. Atomic lock claim. Second concurrent open fails LOCK_NB and exits
//    without side effects. unlink alone is insufficient because PHP
//    keeps the inode alive on open file handles — flock closes the race.
$lock = @fopen(__FILE__, 'r');
if ($lock === false || !flock($lock, LOCK_EX | LOCK_NB)) {
    http_response_code(409);
    exit;
}

// 3. Inline TTL check (defence in depth — systemd reaper sweeps every 30s
//    so worst-case stranded-file lifetime is 60+30 = 90s).
if (filemtime(__FILE__) + __JABALI_TTL_SECONDS__ < time()) {
    http_response_code(410);
    exit;
}

// 4. Bootstrap Drupal. autoload.php lives at the install root; the agent
//    bakes its absolute path in at write time.
$autoloader = require_once __JABALI_AUTOLOAD_PATH__;

$request = \Symfony\Component\HttpFoundation\Request::createFromGlobals();
$kernel  = \Drupal\Core\DrupalKernel::createFromRequest($request, $autoloader, 'prod');
$kernel->boot();
$kernel->preHandle($request);

// 5. Resolve the admin user by username. user_load_by_name is the
//    procedural helper; mirrors what /user/login does.
$admin_username = __JABALI_ADMIN_USERNAME__;
$account = user_load_by_name($admin_username);
if (!$account || !$account->isActive()) {
    error_log('jabali-sso: drupal admin lookup failed for install __JABALI_INSTALL_ID__');
    http_response_code(404);
    exit;
}

// 6. Finalize the login. This sets the session + cookie via Drupal's
//    session handler.
user_login_finalize($account);

// 7. Audit on the WP/Drupal side. Don't log the uid/username.
error_log('jabali-sso: drupal admin login completed for install __JABALI_INSTALL_ID__');

// 8. Don't leak the filename via Referer to downstream admin assets.
header('Referrer-Policy: no-referrer');

// 9. Unlink LAST — after the session is set. Transient failure between
//    here and the redirect leaves the file on disk for a retry; the
//    reaper sweeps stranded files within 90s either way.
@unlink(__FILE__);

// 10. Redirect into the admin area. getBasePath() is correct for
//     subdir installs — /2 in the /2/ case, empty at docroot.
$basePath = rtrim($request->getBasePath(), '/');
header('Location: ' . $basePath . '/user');
exit;
