package commands

import (
	"context"
	"encoding/json"
	"os"
	"path/filepath"
	"testing"
)

// setResolverTestPath points the handler at a temp drop-in so we don't touch
// /etc/systemd/resolved.conf.d on the dev box.
func setResolverTestPath(t *testing.T) string {
	t.Helper()
	dir := t.TempDir()
	path := filepath.Join(dir, "jabali.conf")
	old := resolvedDropInPath
	resolvedDropInPath = path
	t.Cleanup(func() { resolvedDropInPath = old })
	return path
}

// stubResolvedActive replaces systemdResolvedActive for the duration of the
// test so we don't shell out to systemctl.
func stubResolvedActive(t *testing.T, active bool) {
	t.Helper()
	old := systemdResolvedActive
	systemdResolvedActive = func() bool { return active }
	t.Cleanup(func() { systemdResolvedActive = old })
}

// setResolvConfTestPath redirects the /etc/resolv.conf read to a temp path.
// Pass "" to leave no file (absent).
func setResolvConfTestPath(t *testing.T, content string) string {
	t.Helper()
	dir := t.TempDir()
	path := filepath.Join(dir, "resolv.conf")
	if content != "" {
		if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
			t.Fatalf("write resolv.conf: %v", err)
		}
	}
	old := resolvConfPath
	resolvConfPath = path
	t.Cleanup(func() { resolvConfPath = old })
	return path
}

// TestSystemResolverGet_NoDropInNoResolvConf — the nothing-to-report state
// still has to respond with source="none" rather than erroring, because the
// panel renders an empty form from it on a fresh install.
func TestSystemResolverGet_NoDropInNoResolvConf(t *testing.T) {
	setResolverTestPath(t)
	setResolvConfTestPath(t, "")
	stubResolvedActive(t, true)

	resp, err := systemResolverGetHandler(context.Background(), nil)
	if err != nil {
		t.Fatalf("handler error: %v", err)
	}
	got, ok := resp.(systemResolverGetResponse)
	if !ok {
		t.Fatalf("unexpected response type %T", resp)
	}
	if got.Source != "none" {
		t.Errorf("source = %q, want %q", got.Source, "none")
	}
	if len(got.Resolvers) != 0 {
		t.Errorf("resolvers = %v, want empty", got.Resolvers)
	}
	if got.SearchDomain != "" {
		t.Errorf("search = %q, want empty", got.SearchDomain)
	}
}

// TestSystemResolverGet_FallsBackToResolvConf — with our drop-in absent we
// must surface what the host is actually using, so the panel shows the
// admin the current DNS state instead of a blank form.
func TestSystemResolverGet_FallsBackToResolvConf(t *testing.T) {
	setResolverTestPath(t)
	setResolvConfTestPath(t, "# managed by dhcp\nnameserver 10.0.0.1\nnameserver 2001:db8::1\nsearch corp.example\n")
	stubResolvedActive(t, true)

	resp, err := systemResolverGetHandler(context.Background(), nil)
	if err != nil {
		t.Fatalf("handler error: %v", err)
	}
	got := resp.(systemResolverGetResponse)
	if got.Source != "system" {
		t.Errorf("source = %q, want system", got.Source)
	}
	want := []string{"10.0.0.1", "2001:db8::1"}
	if len(got.Resolvers) != len(want) {
		t.Fatalf("resolvers = %v, want %v", got.Resolvers, want)
	}
	for i, r := range want {
		if got.Resolvers[i] != r {
			t.Errorf("resolvers[%d] = %q, want %q", i, got.Resolvers[i], r)
		}
	}
	if got.SearchDomain != "corp.example" {
		t.Errorf("search = %q, want corp.example", got.SearchDomain)
	}
}

// TestSystemResolverGet_DropInWinsOverResolvConf — once an admin has saved
// panel-managed resolvers, the drop-in is the source of truth; we must NOT
// fall back to /etc/resolv.conf even if both files exist.
func TestSystemResolverGet_DropInWinsOverResolvConf(t *testing.T) {
	path := setResolverTestPath(t)
	setResolvConfTestPath(t, "nameserver 10.0.0.1\n")
	stubResolvedActive(t, true)

	content := "[Resolve]\nDNS=1.1.1.1\n"
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatalf("write drop-in: %v", err)
	}

	resp, err := systemResolverGetHandler(context.Background(), nil)
	if err != nil {
		t.Fatalf("handler error: %v", err)
	}
	got := resp.(systemResolverGetResponse)
	if got.Source != "drop-in" {
		t.Errorf("source = %q, want drop-in", got.Source)
	}
	if len(got.Resolvers) != 1 || got.Resolvers[0] != "1.1.1.1" {
		t.Errorf("resolvers = %v, want [1.1.1.1]", got.Resolvers)
	}
}

// TestSystemResolverGet_ResolvConfEmptyReportsNone — resolv.conf exists but
// has no nameserver lines (only comments). Source must be "none", not
// "system", so the UI still shows "no DNS configured".
func TestSystemResolverGet_ResolvConfEmptyReportsNone(t *testing.T) {
	setResolverTestPath(t)
	setResolvConfTestPath(t, "# placeholder\n# generated by nothing\n")
	stubResolvedActive(t, false)

	resp, err := systemResolverGetHandler(context.Background(), nil)
	if err != nil {
		t.Fatalf("handler error: %v", err)
	}
	got := resp.(systemResolverGetResponse)
	if got.Source != "none" {
		t.Errorf("source = %q, want none", got.Source)
	}
	if len(got.Resolvers) != 0 {
		t.Errorf("resolvers = %v, want empty", got.Resolvers)
	}
}

func TestSystemResolverGet_ParsesDropIn(t *testing.T) {
	path := setResolverTestPath(t)
	stubResolvedActive(t, true)

	content := "# Managed\n[Resolve]\nDNS=1.1.1.1 1.0.0.1 2606:4700:4700::1111\nDomains=example.com\n"
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatalf("write fixture: %v", err)
	}

	resp, err := systemResolverGetHandler(context.Background(), nil)
	if err != nil {
		t.Fatalf("handler error: %v", err)
	}
	got := resp.(systemResolverGetResponse)
	if got.Source != "drop-in" {
		t.Errorf("source = %q, want drop-in", got.Source)
	}
	wantResolvers := []string{"1.1.1.1", "1.0.0.1", "2606:4700:4700::1111"}
	if len(got.Resolvers) != len(wantResolvers) {
		t.Fatalf("resolvers = %v, want %v", got.Resolvers, wantResolvers)
	}
	for i, r := range wantResolvers {
		if got.Resolvers[i] != r {
			t.Errorf("resolvers[%d] = %q, want %q", i, got.Resolvers[i], r)
		}
	}
	if got.SearchDomain != "example.com" {
		t.Errorf("search = %q, want example.com", got.SearchDomain)
	}
}

func TestSystemResolverGet_SkipsMalformedLines(t *testing.T) {
	path := setResolverTestPath(t)
	stubResolvedActive(t, false)

	// Invalid IP in DNS= list, garbage line, commented line — all tolerated.
	content := "[Resolve]\nDNS=8.8.8.8 not-an-ip ::1\n# Comment\ngarbage without equals\nDomains=\n"
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatalf("write fixture: %v", err)
	}

	resp, err := systemResolverGetHandler(context.Background(), nil)
	if err != nil {
		t.Fatalf("handler error: %v", err)
	}
	got := resp.(systemResolverGetResponse)
	want := []string{"8.8.8.8", "::1"}
	if len(got.Resolvers) != len(want) {
		t.Fatalf("resolvers = %v, want %v", got.Resolvers, want)
	}
	for i, r := range want {
		if got.Resolvers[i] != r {
			t.Errorf("resolvers[%d] = %q, want %q", i, got.Resolvers[i], r)
		}
	}
	if got.Active {
		t.Errorf("active = true, want false")
	}
}

func TestSystemResolverGet_Registered(t *testing.T) {
	t.Parallel()
	for _, name := range Default.Commands() {
		if name == "system.resolver.get" {
			return
		}
	}
	t.Fatal("system.resolver.get not registered")
}

// TestSystemResolverGet_JSONShape freezes the wire contract for the panel.
// Any change to the field names here is a cross-boundary break.
func TestSystemResolverGet_JSONShape(t *testing.T) {
	t.Parallel()
	raw, err := json.Marshal(systemResolverGetResponse{
		Active:       true,
		Resolvers:    []string{"1.1.1.1"},
		SearchDomain: "example.com",
		Source:       "drop-in",
	})
	if err != nil {
		t.Fatalf("marshal: %v", err)
	}
	var got map[string]any
	if err := json.Unmarshal(raw, &got); err != nil {
		t.Fatalf("unmarshal: %v", err)
	}
	for _, key := range []string{"active", "resolvers", "search_domain", "source"} {
		if _, ok := got[key]; !ok {
			t.Errorf("missing key %q in %s", key, raw)
		}
	}
}
