package commands

import (
	"fmt"
	"sort"
	"strings"
)

// EgressUser is one user-policy snapshot consumed by the renderer.
// Username drives the slice path AND the chain/counter names; State
// selects which chain (enforced/learning) is jumped to from the vmap.
// Off-state users get NO entry — the slice falls through to default
// accept outside this table.
//
// AllowedExtra entries are pre-validated by the panel-api layer; we
// emit them verbatim into the chain. The agent does not re-validate
// CIDRs or ports here — defence-in-depth lives in the API handler.
type EgressUser struct {
	Username     string
	State        string // "off" | "learning" | "enforced"
	AllowedExtra []EgressExtra
}

// EgressExtra is one allowed-destination override for a user. Port +
// Protocol are optional. Comment is for the human auditor only and is
// emitted as an `# inline comment` on the rule.
type EgressExtra struct {
	CIDR     string
	Port     *int
	Protocol string // "tcp" or "udp"; "" defaults to "tcp"
	Comment  string
}

// EgressDefaults captures the global default allowlist (M34 Step 6 will
// surface this as server_settings columns; Step 2 hard-codes the
// canonical set in the renderer call site).
type EgressDefaults struct {
	Loopback4 []string // CIDRs
	Loopback6 []string // CIDRs
	PortsTCP  []int
	PortsUDP  []int
}

// CanonicalDefaults returns the safe-by-default allowlist. Removing any
// of these would silently break the typical LAMP workload (memory pin
// in plans/m34: loopback for MariaDB/Redis socket DSN drift, :443 for
// wp-cron/Composer/apt, :587/:465/:25 for mail() submission).
func CanonicalDefaults() EgressDefaults {
	return EgressDefaults{
		Loopback4: []string{"127.0.0.0/8", "10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"},
		Loopback6: []string{"::1/128", "fc00::/7", "fe80::/10"},
		PortsTCP:  []int{53, 80, 443, 587, 465, 25},
		PortsUDP:  []int{53},
	}
}

// RenderEgressNFT produces the deterministic /etc/nftables.d/jabali-per-user-egress.nft
// content from the in-memory snapshot. Output is sorted by username so
// the file is reproducible across reconciler ticks (idempotent file-
// hash check by callers).
//
// Cgroup path matches the M18 slice topology (verified on test VM
// 2026-04-29): jabali.slice/jabali-user.slice/jabali-user-<USERNAME>.slice
// at depth 3 of /sys/fs/cgroup. nftables `socket cgroupv2 level 3` is
// the matcher, with vmap dispatch keyed on the full cgroup path.
//
// Users whose slice does not exist on disk (existsFn returns false) are
// skipped with a comment marker; nft would otherwise reject the file
// at parse time because the kernel verifies cgroupv2 paths exist on
// the host before accepting the element.
func RenderEgressNFT(users []EgressUser, defaults EgressDefaults, existsFn func(slicePath string) bool) string {
	if existsFn == nil {
		existsFn = defaultSliceExists
	}

	sorted := make([]EgressUser, len(users))
	copy(sorted, users)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].Username < sorted[j].Username })

	var b strings.Builder
	b.WriteString("# Generated by jabali (panel-agent) — do not edit.\n")
	b.WriteString("# Source of truth: user_egress_policies. Reload via:\n")
	b.WriteString("#   nft -f /etc/nftables.d/jabali-per-user-egress.nft\n\n")

	b.WriteString("table inet jabali_per_user {\n")

	// Default sets — referenced from every per-user chain.
	if len(defaults.Loopback4) > 0 {
		b.WriteString("  set default_loopback4 {\n")
		b.WriteString("    type ipv4_addr; flags interval;\n")
		fmt.Fprintf(&b, "    elements = { %s }\n", strings.Join(defaults.Loopback4, ", "))
		b.WriteString("  }\n")
	}
	if len(defaults.Loopback6) > 0 {
		b.WriteString("  set default_loopback6 {\n")
		b.WriteString("    type ipv6_addr; flags interval;\n")
		fmt.Fprintf(&b, "    elements = { %s }\n", strings.Join(defaults.Loopback6, ", "))
		b.WriteString("  }\n")
	}
	if len(defaults.PortsTCP) > 0 {
		b.WriteString("  set default_ports_tcp {\n")
		b.WriteString("    type inet_service;\n")
		fmt.Fprintf(&b, "    elements = { %s }\n", joinInts(defaults.PortsTCP, ", "))
		b.WriteString("  }\n")
	}
	if len(defaults.PortsUDP) > 0 {
		b.WriteString("  set default_ports_udp {\n")
		b.WriteString("    type inet_service;\n")
		fmt.Fprintf(&b, "    elements = { %s }\n", joinInts(defaults.PortsUDP, ", "))
		b.WriteString("  }\n")
	}

	// Per-user counters + chains. Skip off-state and missing-slice users.
	type rendered struct {
		username string
		state    string
	}
	var emitted []rendered

	for _, u := range sorted {
		if u.State == "off" {
			fmt.Fprintf(&b, "\n  # %s: state=off — skipped (falls through to default accept)\n", u.Username)
			continue
		}
		slicePath := SlicePathFor(u.Username)
		if !existsFn(slicePath) {
			fmt.Fprintf(&b, "\n  # %s: slice %s missing on host — skipped\n", u.Username, slicePath)
			continue
		}
		fmt.Fprintf(&b, "\n  counter user_%s_drops {}\n", u.Username)
		writeUserChain(&b, u, defaults)
		emitted = append(emitted, rendered{u.Username, u.State})
	}

	// vmap dispatch by cgroup path (level 3). Empty if no users emitted —
	// then the chain still exists but matches nothing, falling through
	// to the policy accept.
	b.WriteString("\n  map cgroup_to_chain {\n")
	b.WriteString("    type cgroupsv2 : verdict\n")
	if len(emitted) > 0 {
		b.WriteString("    elements = {\n")
		for i, r := range emitted {
			sep := ","
			if i == len(emitted)-1 {
				sep = ""
			}
			fmt.Fprintf(&b, "      \"%s\" : jump user_%s_%s%s\n",
				SlicePathFor(r.username), r.username, r.state, sep)
		}
		b.WriteString("    }\n")
	}
	b.WriteString("  }\n")

	b.WriteString("\n  chain output {\n")
	b.WriteString("    type filter hook output priority 0; policy accept;\n")
	b.WriteString("    socket cgroupv2 level 3 vmap @cgroup_to_chain\n")
	b.WriteString("  }\n")
	b.WriteString("}\n")

	return b.String()
}

// SlicePathFor returns the full cgroup path under /sys/fs/cgroup that
// nftables type=cgroupsv2 expects for one user. Mirrors the M18 slice
// hierarchy exactly.
func SlicePathFor(username string) string {
	return fmt.Sprintf("jabali.slice/jabali-user.slice/jabali-user-%s.slice", username)
}

func writeUserChain(b *strings.Builder, u EgressUser, d EgressDefaults) {
	chainName := fmt.Sprintf("user_%s_%s", u.Username, u.State)
	fmt.Fprintf(b, "\n  chain %s {\n", chainName)

	if len(d.Loopback4) > 0 {
		b.WriteString("    ip daddr @default_loopback4 accept\n")
	}
	if len(d.Loopback6) > 0 {
		b.WriteString("    ip6 daddr @default_loopback6 accept\n")
	}
	if len(d.PortsTCP) > 0 {
		b.WriteString("    tcp dport @default_ports_tcp accept\n")
	}
	if len(d.PortsUDP) > 0 {
		b.WriteString("    udp dport @default_ports_udp accept\n")
	}

	for _, ex := range u.AllowedExtra {
		writeExtra(b, ex)
	}

	switch u.State {
	case "enforced":
		fmt.Fprintf(b, "    counter name user_%s_drops drop\n", u.Username)
	case "learning":
		// Rate-limit the dmesg log so a runaway loop doesn't drown the
		// kernel ring buffer. Counter still bumps every drop so the
		// M14 burst source sees the true rate.
		fmt.Fprintf(b, "    limit rate 5/minute log prefix \"jabali-egress-learn-%s \" group 0\n", u.Username)
		fmt.Fprintf(b, "    counter name user_%s_drops accept\n", u.Username)
	}

	b.WriteString("  }\n")
}

func writeExtra(b *strings.Builder, ex EgressExtra) {
	proto := ex.Protocol
	if proto == "" {
		proto = "tcp"
	}
	family := "ip"
	if strings.Contains(ex.CIDR, ":") {
		family = "ip6"
	}
	var rule string
	if ex.Port != nil {
		rule = fmt.Sprintf("    %s daddr %s %s dport %d accept", family, ex.CIDR, proto, *ex.Port)
	} else {
		rule = fmt.Sprintf("    %s daddr %s accept", family, ex.CIDR)
	}
	if ex.Comment != "" {
		rule += fmt.Sprintf(" comment \"%s\"", strings.ReplaceAll(ex.Comment, "\"", "'"))
	}
	b.WriteString(rule + "\n")
}

func joinInts(in []int, sep string) string {
	parts := make([]string, len(in))
	for i, v := range in {
		parts[i] = fmt.Sprintf("%d", v)
	}
	return strings.Join(parts, sep)
}
